version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./sites:/var/www/sites
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - web
    depends_on:
      - site1-app
      # - site2-app
      # - site3-app
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  site1-app:
    image: site1-image # Replace with actual image
    networks:
      - web
    environment:
      - VIRTUAL_HOST=site1.com
    restart: unless-stopped

  # site2-app:
  #   image: site2-image  # Replace with actual image
  #   networks:
  #     - web
  #   environment:
  #     - VIRTUAL_HOST=site2.com
  #   restart: unless-stopped

  # site3-app:
  #   image: site3-image  # Replace with actual image
  #   networks:
  #     - web
  #   environment:
  #     - VIRTUAL_HOST=site3.com
  #   restart: unless-stopped

networks:
  web:
    driver: bridge
