services:
  nushell:
    image: ghcr.io/nushell/nushell:latest-alpine
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/work
    working_dir: /work
    entrypoint: ["nu"]

volumes:
  nushell_config:
