version: "3.8"

services:
  nushell:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETARCH: ${TARGETARCH}
        BUILD_REF: ${BUILD_REF}
        BUILD_DATE: ${BUILD_DATE}
        RELEASE_QUERY_API: "https://api.github.com/repos/nushell/nushell/releases/latest"
    image: nushell:latest
    environment:
      - TARGETARCH=${TARGETARCH}
    volumes:
      - nushell_config:/home/nushell/.config/nushell
    working_dir: /home/nushell
    entrypoint: ["nu"]
    user: nushell

volumes:
  nushell_config:
